name = "blog"
main = "worker.js"
compatibility_date = "2024-01-07"

[build]
command = "powershell -ExecutionPolicy Bypass -File build.ps1"

[env.production]
name = "blog-prod"
route = "https://aac185ca.lacie.pages.dev/*" 